kind: Namespace
apiVersion: v1
metadata:
  name: apps
  labels:
    name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-workers
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-workers
  template:
    metadata:
      labels:
        app: multi-workers
    spec:
      containers:
      - name: multi-process
        image: ghcr.io/yktakaha4/worker-testing:c5dc7c9dab9d1f53f4d423836b4bdd8fa3e78594
        command:
          - python
          - -m
          - gunicorn
          - apps.asgi:application
          - -k
          - uvicorn.workers.UvicornWorker
          - -w
          - "4"
        ports:
          - protocol: TCP
            containerPort: 8000
        resources:
          requests:
            cpu: 1000m
            memory: 4096Mi
          limits:
            memory: 4096Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-worker
  namespace: apps
spec:
  replicas: 4
  selector:
    matchLabels:
      app: single-worker
  template:
    metadata:
      labels:
        app: single-worker
    spec:
      containers:
      - name: multi-process
        image: ghcr.io/yktakaha4/worker-testing:c5dc7c9dab9d1f53f4d423836b4bdd8fa3e78594
        command:
          - python
          - -m
          - uvicorn
          - apps.asgi:application
          - --workers
          - "1"
        ports:
          - protocol: TCP
            containerPort: 8000
        resources:
          requests:
            cpu: 250m
            memory: 1024Mi
          limits:
            memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: multi-workers
  namespace: apps
spec:
  selector:
      app: multi-workers
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: single-worker
  namespace: apps
spec:
  selector:
      app: single-worker
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
